import type { Project, Experience, Skill } from "@/types";

export const PERSONAL = {
  name: "Satvik Sabharwal",
  email: "createwithsatvik@gmail.com",
  github: "https://github.com/satviksabharwal",
  linkedin: "https://www.linkedin.com/in/satvik-sabharwal/",
  location: "Berlin, Germany",
};

export const SKILLS: Skill[] = [
  { name: "React / Next.js", level: 97, category: "frontend" },
  { name: "JavaScript", level: 95, category: "frontend" },
  { name: "TypeScript", level: 94, category: "frontend" },
  { name: "Tailwind CSS", level: 95, category: "frontend" },
  { name: "Three.js / WebGL", level: 55, category: "frontend" },
  { name: "Node.js", level: 60, category: "backend" },
  { name: "REST API", level: 60, category: "backend" },
  { name: "PostgreSQL", level: 55, category: "backend" },
  { name: "Docker", level: 20, category: "tools" },
  { name: "CI/CD (GitHub Actions)", level: 80, category: "tools" },
  { name: "Figma / Design Systems", level: 88, category: "tools" },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "PhotoVoltaic System",
    descriptionKey: "photoVoltaic",
    tech: ["React", "TypeScript", "Node.js", "Express.js", "Supabase", "MaterialUI"],
    github: "https://github.com/satviksabharwal/PhotoVoltaic-System",
    link: "https://thesolarsense.online/",
    featured: true,
    color: "#00f5c4",
  },
  {
    id: 2,
    title: "CalorieCam",
    descriptionKey: "calorieCam",
    tech: ["React", "TypeScript", "Node.js", "Express.js", "Supabase", "TailwindCSS"],
    github: "https://github.com/satviksabharwal/calorie-cam-metrics",
    link: "https://app.calorie-cam.workers.dev/",
    featured: true,
    color: "#a78bfa",
  },
  {
    id: 3,
    title: "Sci-fi inspired Portfolio",
    descriptionKey: "portfolio",
    tech: ["Next.js", "TypeScript", "TailwindCSS", "Three.js", "Framer Motion"],
    github: "https://github.com/satviksabharwal/sci-fi-3D-portfolio",
    link: "http://satviksabharwal.com/",
    featured: true,
    color: "#38bdf8",
  },
   {
    id: 4,
    title: "Data Management Platform",
    descriptionKey: "dataManagement",
    tech: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB"],
    github: "https://github.com/satviksabharwal/data-management-platform",
    link: "",
    featured: true,
    color: "#facc15",
  },
   {
    id: 5,
    title: "3D Personal Portfolio Website",
    descriptionKey: "portfolio3d",
    tech: ["React", "JavaScript", "CSS", "Three.js", "WebGL"],
    github: "",
    link: "https://satviksabharwal.netlify.app/",
    featured: true,
    color: "#f472b6",
  },
  {
    id: 6,
    title: "Coming soon",
    descriptionKey: "comingSoon",
    tech: ["Information"],
    link: "",
    featured: false,
    color: "#fb923c",
  },
];

export const EXPERIENCE: Experience[] = [
  {
    id: 1,
    role: "Frontend Engineer",
    company: "Staffbase SE",
    period: "2022 — Present",
    descriptionNamespace: "staffbase",
    tech: [
      "React",
      "TypeScript",
      "TailwindCSS",
      "Zustand",
      "React Query",
      "i18next",
      "Vitest",
      "Jest",
      "Visx",
    ],
    current: true,
  },
  {
    id: 2,
    role: "Senior Engineer",
    company: "Brillio",
    period: "2021 — 2021",
    descriptionNamespace: "brillio",
    tech: [
      "React",
      "TypeScript",
      "StyledComponents",
      "Redux",
      "StyledComponents",
      "MaterialUI",
    ],
  },
  {
    id: 3,
    role: "Project Engineer",
    company: "Wipro",
    period: "2019 — 2021",
    descriptionNamespace: "wipro",
    tech: ["React", "JavaScript", "CSS"],
  },
];
